# Generated by Django 5.1.4 on 2024-12-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='maxlength',
        ),
        migrations.RemoveField(
            model_name='fields',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='fields',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
