# Generated by Django 5.1.4 on 2024-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fields_maxlength_remove_fields_placeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('radio', 'Radio'), ('file', 'File'), ('image', 'Image')], max_length=20),
        ),
    ]
