# Generated by Django 5.1.4 on 2024-12-28 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fields_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardfieldvalues',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.cards'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardfieldvalues',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.fields'),
            preserve_default=False,
        ),
    ]
