# Generated by Django 5.1.4 on 2024-12-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardfieldvalues_card_cardfieldvalues_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.phases'),
        ),
    ]
